language: cpp
compiler: gcc
sudo: required
before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq
install:
- sudo pip install cpp-coveralls
- sudo apt-get install -qq g++-4.8
- export CXX="g++-4.8"
script:
- make
after_success:
- "./tikz3d"
- coveralls --exclude lib --exclude include --gcov-options
  '\-lp'
- export REPO_NAME=${TRAVIS_REPO_SLUG#*/}
notifications:
  email:
    on_success: change
    on_failure: change
branches:
  only: master
os: linux
