language: cpp
compiler: gcc
sudo: required
before_install:
- sudo apt-get update -qq
- sudo pip install cpp-coveralls
script:
- make
after_success:
- "./tikz3d"
- coveralls --exclude lib --exclude include --gcov-options
  '\-lp'
- export REPO_NAME=${TRAVIS_REPO_SLUG#*/}
notifications:
  email:
    on_success: change
    on_failure: change
branches:
  only: master
os: linux
