language: cpp
compiler: gcc
sudo: required
before_install:
- openssl aes-256-cbc -K $encrypted_e1686f423df6_key -iv $encrypted_e1686f423df6_iv
  -in travisci_rsa.enc -out travisci_rsa -d
- chmod 0600 travisci_rsa
- cp travisci_rsa ~/.ssh/id_rsa
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq
- sudo apt-get install -y libarmadillo2 libarmadillo-dev
- sudo pip install cpp-coveralls
script:
- make
after_success:
- "./divopt"
- coveralls --exclude lib --exclude include --exclude src/c_logger.cpp --gcov-options
  '\-lp'
- export REPO_NAME=${TRAVIS_REPO_SLUG#*/}
- sudo apt-get --no-install-recommends install doxygen
- doxygen config.doxygen
- cd ..
- git clone https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
- cd gh-pages
- git config user.name "njanetos"
- git config user.email "nejanetos@gmail.com"
- git checkout gh-pages
- git pull origin gh-pages
- git rm -rf .
- mv -v ${TRAVIS_BUILD_DIR}/documentation/* .
- git add . -A
- CHANGESET=$(git rev-parse --verify HEAD)
- git commit -m "Automatic Travis update of documentation ${CHANGESET}"
- git remote set-url origin git@github.com:njanetos/divopt.git
- git push origin
notifications:
  email:
    on_success: change
    on_failure: change
branches:
  only: master
os: linux
